apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coffee-testing-pipeline
  namespace: argocd
spec:
  destination:
    namespace: tekton-pipelines
    server: https://kubernetes.default.svc
  project: default
  source:
    path: pipeline
    repoURL: https://github.com/amine620/complete-ci-tekton-argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
---
